/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.61
 * Generated at: 2016-02-10 09:52:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.iijp.service.GetDepartments;
import com.iijp.model.*;
import java.util.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<title>photo_style</title>\r\n");
      out.write("  <meta name=\"description\" content=\"website description\" />\r\n");
      out.write("  <meta name=\"keywords\" content=\"website keywords, website keywords\" />\r\n");
      out.write("  <meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\" />\r\n");
      out.write("  <!-- modernizr enables HTML5 elements and feature detects -->\r\n");
      out.write("  <script type=\"text/javascript\" src=\"modernizr-1.5.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <div id=\"main\">\r\n");
      out.write("    <header>\r\n");
      out.write("      <div id=\"logo\">\r\n");
      out.write("        <div id=\"logo_text\">\r\n");
      out.write("          <!-- class=\"logo_colour\", allows you to change the colour of the text -->\r\n");
      out.write("          <h1><font size=5px><a href=\"\">INFOGAIN JOB<span class=\"logo_colour\">PORTAL</span></a></font></h1>\r\n");
      out.write("\t\t\t<img src=\"logo.jpg\" height=60 width=220/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <nav>\r\n");
      out.write("        <ul class=\"sf-menu\" id=\"nav\">\r\n");
      out.write("          <li class=\"selected\"><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("          <li><a href=\"New folder/form.jsp\">Login</a></li>\r\n");
      out.write("          <li><a href=\"Organise.html\">Organisation chart</a></li>\r\n");
      out.write("          <li><a href=\"#\">JOBS</a>\r\n");
      out.write("            <ul>\r\n");
      out.write("              <li><a href=\"#\">Jobs By Location</a>\r\n");
      out.write("              <ul>\r\n");
      out.write("\t\t\t  ");

			  GetDepartments get=new GetDepartments();
			  ArrayList<Branch> branch=get.getBranch();
			  ArrayList<String> jobnames=get.getJobNames();
			  ArrayList<Departments> departments=get.getdepartments();
			  for(Branch b:branch)
			  {
			  
      out.write("\r\n");
      out.write("\t\t\t   \r\n");
      out.write("                  <li><a href=\"New folder/form.jsp\">");
      out.print(b.getBranch_name() );
      out.write(" </a></li>\r\n");
      out.write("                  \r\n");
      out.write("               \r\n");
      out.write("                ");

               }
                
      out.write("\r\n");
      out.write("                </ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("              <li><a href=\"#\">Jobs By Designation</a>\r\n");
      out.write("              <ul>\r\n");
      out.write("              ");

              for(String j:jobnames)
			  {
              
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                  <li><a href=\"New folder/form.jsp\">");
      out.print(j );
      out.write(" </a></li>\r\n");
      out.write("                  \r\n");
      out.write("                \r\n");
      out.write("                ");

			  }
                
      out.write("\r\n");
      out.write("                </ul>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li><a href=\"#\">Jobs By Departments</a>\r\n");
      out.write("               <ul>\r\n");
      out.write("              ");

              for(Departments d:departments)
              {
              
              
      out.write("\r\n");
      out.write("\t\t\t  \r\n");
      out.write("                  <li><a href=\"New folder/form.jsp\">");
      out.print(d.getDepartment_name() );
      out.write(" </a></li>\r\n");
      out.write("                 \r\n");
      out.write("                \r\n");
      out.write("                 ");

              }
              
      out.write("\t\r\n");
      out.write("              </ul>  \r\n");
      out.write("\t\t\t  </li>\r\n");
      out.write("        \r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("\t\t  \r\n");
      out.write("          <li><a href=\"contact.html\">Contact Us</a></li>\r\n");
      out.write("\t\t     \r\n");
      out.write("\t\t\t\r\n");
      out.write("       \r\n");
      out.write("        </ul>\r\n");
      out.write("      </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("    <div id=\"site_content\">\r\n");
      out.write("      <div id=\"sidebar_container\">\r\n");
      out.write("        <div class=\"gallery\">\r\n");
      out.write("          <ul class=\"images\">\r\n");
      out.write("            <li class=\"show\"><img width=\"450\" height=\"450\" src=\"1.jpg\" alt=\"photo_one\" /></li>\r\n");
      out.write("            <li><img width=\"450\" height=\"450\" src=\"2.jpg\" alt=\"photo_two\" /></li>\r\n");
      out.write("            <li><img width=\"450\" height=\"450\" src=\" 3.jpg\" alt=\"photo_three\" /></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div id=\"content\">\r\n");
      out.write("        <h1><font size=6px>Latest Jobs</font></h1>\r\n");
      out.write("        <p><font size=3px>Responsible for supervising promotions programs to incentivize \r\n");
      out.write("        the point-of-employee-satisfaction.</font></p>\r\n");
      out.write("\t\t\t<p>A Transparent system allowing everyone \r\n");
      out.write("\t\t\tto play fair and get deserving promotions</p>\r\n");
      out.write("\t\t<p>Explore our exciting career opportunities\r\n");
      out.write("\t\t across technical, non-technical and BPO categories.</p>\r\n");
      out.write("\t\t<p>A place that empowers people who perform</p>\r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <footer>\r\n");
      out.write("      <p>Copyright &copy; 2015 Infogain Corporation. All rights reserved.</p>\r\n");
      out.write("    </footer>\r\n");
      out.write("  </div>\r\n");
      out.write("  <p>&nbsp;</p>\r\n");
      out.write("  <!-- javascript at the bottom for fast page loading -->\r\n");
      out.write("  <script type=\"text/javascript\" src=\"jquery.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"jquery.easing-sooper.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"jquery.sooperfish.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"image_fade.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\">\r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("      $('ul.sf-menu').sooperfish();\r\n");
      out.write("    });\r\n");
      out.write("  </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
