/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.61
 * Generated at: 2016-02-10 09:52:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.New_0020folder;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class form_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write(" <head>\r\n");
      out.write("        <title>Login Page</title>\r\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"/>\r\n");
      out.write("        <meta name=\"description\" content=\"Expand, contract, animate forms with jQuery wihtout leaving the page\" />\r\n");
      out.write("        <meta name=\"keywords\" content=\"expand, form, css3, jquery, animate, width, height, adapt, unobtrusive javascript\"/>\r\n");
      out.write("\t\t<link rel=\"shortcut icon\" href=\"../favicon.ico\" type=\"image/x-icon\"/>\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\" />\r\n");
      out.write("\t\t<script src=\"js/cufon-yui.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t\t<script src=\"js/ChunkFive_400.font.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\tCufon.replace('h1',{ textShadow: '1px 1px #fff'});\r\n");
      out.write("\t\t\tCufon.replace('h2',{ textShadow: '1px 1px #fff'});\r\n");
      out.write("\t\t\tCufon.replace('h3',{ textShadow: '1px 1px #000'});\r\n");
      out.write("\t\t\tCufon.replace('.back');\r\n");
      out.write("\t\t</script>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("    ");
 String errorMsg[]=(String[])session.getAttribute("errorList"); 
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\t<center><h1><font color=\"white\">Login</font></h1></center>\r\n");
      out.write("\t\t<div class=\"wrapper\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t<div id=\"form_wrapper\" class=\"form_wrapper\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<form class=\"login active\" action=\"../ValidateServlet\" >\r\n");
      out.write("\t\t\t\t\t\t<h3>Login</h3>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t");
if(errorMsg!=null)
						{ if(errorMsg[0]!=null){
      out.write(" \r\n");
      out.write("\t\t\t\t\t\t");
      out.print(errorMsg[0]);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
} if(errorMsg[1]!=null){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(errorMsg[1] );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
} if(errorMsg[4]!=null){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(errorMsg[4]);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
}} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<label>User Id:</label>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"userId\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"error\">This is an error</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t");
if(errorMsg!=null)
						{ if(errorMsg[2]!=null){
      out.write(" \r\n");
      out.write("\t\t\t\t\t\t");
      out.print(errorMsg[2]);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
} if(errorMsg[3]!=null){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(errorMsg[3] );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
}} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<label>Password: <a href=\"forgot_password.jsp\" rel=\"forgot_password\" class=\"forgot linkform\">Forgot your password?</a></label>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"password\" name=\"password\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"error\">This is an error</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"bottom\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"remember\"><input type=\"checkbox\" /><span>Keep me logged in</span></div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" style=\"height:30px;width:150px\">login</button>\t \r\n");
      out.write("\t\t\t\t\t<!-- <a href=\"../ValidateServlet\"><font size=6px>Login</font></a> -->\r\n");
      out.write("\t\t\t\t\t \t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t<form class=\"forgot_password\">\r\n");
      out.write("\t\t\t\t\t\t<h3>Forgot Password</h3>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<label>Username or Email:</label>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"forgetPassword\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"error\">This is an error</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"bottom\">\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"submit\" value=\"Send reminder\"></input>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"index.jsp\" rel=\"login\" class=\"linkform\">Suddenly remebered? Log in here</a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- The JavaScript -->\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t$(function() {\r\n");
      out.write("\t\t\t\t\t//the form wrapper (includes all forms)\r\n");
      out.write("\t\t\t\tvar $form_wrapper\t= $('#form_wrapper'),\r\n");
      out.write("\t\t\t\t\t//the current form is the one with class active\r\n");
      out.write("\t\t\t\t\t$currentForm\t= $form_wrapper.children('form.active'),\r\n");
      out.write("\t\t\t\t\t//the change form links\r\n");
      out.write("\t\t\t\t\t$linkform\t\t= $form_wrapper.find('.linkform');\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t//get width and height of each form and store them for later\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t$form_wrapper.children('form').each(function(i){\r\n");
      out.write("\t\t\t\t\tvar $theForm\t= $(this);\r\n");
      out.write("\t\t\t\t\t//solve the inline display none problem when using fadeIn fadeOut\r\n");
      out.write("\t\t\t\t\tif(!$theForm.hasClass('active'))\r\n");
      out.write("\t\t\t\t\t\t$theForm.hide();\r\n");
      out.write("\t\t\t\t\t$theForm.data({\r\n");
      out.write("\t\t\t\t\t\twidth\t: $theForm.width(),\r\n");
      out.write("\t\t\t\t\t\theight\t: $theForm.height()\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//set width and height of wrapper (same of current form)\r\n");
      out.write("\t\t\t\tsetWrapperWidth();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t/*\r\n");
      out.write("\t\t\t\tclicking a link (change form event) in the form\r\n");
      out.write("\t\t\t\tmakes the current form hide.\r\n");
      out.write("\t\t\t\tThe wrapper animates its width and height to the \r\n");
      out.write("\t\t\t\twidth and height of the new current form.\r\n");
      out.write("\t\t\t\tAfter the animation, the new form is shown\r\n");
      out.write("\t\t\t\t*/\r\n");
      out.write("\t\t\t\t$linkform.bind('click',function(e){\r\n");
      out.write("\t\t\t\t\tvar $link\t= $(this);\r\n");
      out.write("\t\t\t\t\tvar target\t= $link.attr('rel');\r\n");
      out.write("\t\t\t\t\t$currentForm.fadeOut(400,function(){\r\n");
      out.write("\t\t\t\t\t\t//remove class active from current form\r\n");
      out.write("\t\t\t\t\t\t$currentForm.removeClass('active');\r\n");
      out.write("\t\t\t\t\t\t//new current form\r\n");
      out.write("\t\t\t\t\t\t$currentForm= $form_wrapper.children('form.'+target);\r\n");
      out.write("\t\t\t\t\t\t//animate the wrapper\r\n");
      out.write("\t\t\t\t\t\t$form_wrapper.stop()\r\n");
      out.write("\t\t\t\t\t\t\t\t\t .animate({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth\t: $currentForm.data('width') + 'px',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\theight\t: $currentForm.data('height') + 'px'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t },500,function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t//new form gets class active\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$currentForm.addClass('active');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t//show the new form\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$currentForm.fadeIn(400);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t });\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tfunction setWrapperWidth(){\r\n");
      out.write("\t\t\t\t\t$form_wrapper.css({\r\n");
      out.write("\t\t\t\t\t\twidth\t: $currentForm.data('width') + 'px',\r\n");
      out.write("\t\t\t\t\t\theight\t: $currentForm.data('height') + 'px'\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t/*\r\n");
      out.write("\t\t\t\tfor the demo we disabled the submit buttons\r\n");
      out.write("\t\t\t\tif you submit the form, you need to check the \r\n");
      out.write("\t\t\t\twhich form was submited, and give the class active \r\n");
      out.write("\t\t\t\tto the form you want to show\r\n");
      out.write("\t\t\t\t*/\r\n");
      out.write("\t\t\t\t$form_wrapper.find('input[type=\"submit\"]')\r\n");
      out.write("\t\t\t\t\t\t\t .click(function(e){\r\n");
      out.write("\t\t\t\t\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\t\t\t\t });\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("        </script>\r\n");
      out.write("    </body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
